name: Node.js CI

on:
  push:
    branches:
      - feat/*
      - fix/*
      - chore/*
  pull_request:
    branches:
      - master

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch at $GITHUB_WORKSPACE
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn run test
      - name: Run eslint
        run: yarn run lint
