name: Node.js CI

on:
  push:
    branches:
      - feat/*
      - fix/*
      - chore/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: yarn install --frozen-lockfile
    - run: yarn run test
    - run: yarn run lint
