name: dev_sync deployment to ec2

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: ssh deploy
    environment: test_ec2
    runs-on: ubuntu-latest
    steps:
      - name: ssh connect
        uses: appleboy/ssh-action@v1.0.0
        env:
          INPUT_BRANCH_NAME: ${{ vars.INPUT_BRANCH_NAME }}
          INPUT_SERVER_NAME: ${{ vars.INPUT_SERVER_NAME }}
          INPUT_APP_UNDER_MAINTAINANCE: ${{vars.INPUT_APP_UNDER_MAINTAINANCE}}
        with:
          host: ${{ secrets.INPUT_SSH_HOST }}
          username: ${{secrets.INPUT_SSH_USER_NAME}}
          key: ${{secrets.INPUT_SSH_PRIVATE_KEY}}
          allenvs: true
          debug: true
          script: |
            cd ~/projects/book-review-graphql-BE/ 
            echo "BRANCH_NAME FROM OUTER" $BRANCH_NAME 
            git pull origin $BRANCH_NAME 
            bash -s < .github/workflows/script.sh
            SCRIPT_STATUS=$?
            if [[ $SCRIP_STATUS != 0 ]]; then exit $DEPLOYMENT_STATUS ; fi
